DROP TABLE IF EXISTS question;
DROP TABLE IF EXISTS poll_answer;

CREATE TABLE question (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(300) UNIQUE NOT NULL,
    first_answer VARCHAR(300) NOT NULL,
    second_answer VARCHAR(300) NOT NULL,
    third_answer VARCHAR(300) NOT NULL,
    fourth_answer VARCHAR(300) NOT NULL
);

CREATE TABLE poll_answer (
    answer_number INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    question_id INT NOT NULL,
    date_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    selected_answer VARCHAR(300),
    UNIQUE (user_id, question_id), -- Ensure unique combination
    FOREIGN KEY (question_id) REFERENCES question(id)
);
